name 'base'
version '0.2.16'

depends 'chef-client'
depends 'consul'
depends 'fail2ban'
depends 'firewall'
depends 'git'
depends 'omnibus_updater'
depends 'packagecloud'
depends 'papertrail'
depends 'rsyslog'
depends 'sudo'
depends 'ubuntu'
depends 'ufw'
depends 'user'
