name 'base'
version '0.4.0'

depends 'chef_client_updater'
depends 'consul'
depends 'fail2ban'
depends 'firewall'
depends 'git'
depends 'packagecloud'
depends 'rsyslog'
depends 'sudo'
depends 'ubuntu'
depends 'ufw'
depends 'user'
