#cloud-config
write_files:
- path: /etc/chef/client.rb
  permissions: '0644'
  owner: root:wheel
  content: |
    chef_server_url "${chef_server_url}"
    json_attribs "/etc/chef/firstboot.json"
- path: /etc/chef/validation.pem
  permissions: '0644'
  owner: root:wheel
  content: ${jsonencode(chef_validation_key)}
- path: /etc/chef/firstboot.json
  permissions: '0644'
  owner: root:wheel
  content: |
    ${jsonencode(chef_attributes)}
- path: /etc/chef/touch

packages:
  - rubygem-chef-bin

runcmd:
- "/usr/local/bin/chef-client --chef-license accept"
